# ASSIGNMENT
Write a NumPy program and find the product of 2-dim arrays and a 3-dim Array
Do a simple calculation using: Sin, Cos, Tan, Log
Write a NumPy program to multiply a 5x3 matrix using Matmul
Write a NumPy program to create a 3x3 identity matrix
Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10
Write a NumPy program to create a new shape to an array without changing its data(for example a 3X2 matrix to a 2x3 matrix)

In [78]:
import numpy as np

In [79]:
b = np.arange (9). reshape (3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
#Write a NumPy program and find the product of 2-dim arrays and a 3-dim Array
k = np.arange (6). reshape(2,3)
k

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
l = np.arange (9). reshape(3,3)
l

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
np.dot(k,l)

array([[15, 18, 21],
       [42, 54, 66]])

In [61]:
#Do a simple calculation using: Sin, Cos, Tan, Log
np.sin(30)

-0.9880316240928618

In [83]:
np.cos(l)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003]])

In [84]:
np.tan(l)

array([[ 0.        ,  1.55740772, -2.18503986],
       [-0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -6.79971146]])

In [89]:
np.log (10) 

2.302585092994046

In [65]:
#Write a NumPy program to multiply a 5x3 matrix using Matmul
h = np.arange(15). reshape (3,5)
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
o = np.arange (15,30). reshape(5,3)
o

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [67]:
np.matmul(h, o)

array([[ 240,  250,  260],
       [ 765,  800,  835],
       [1290, 1350, 1410]])

In [68]:
a = [[1,2], [2,4]]
b = [[5,6], [7,8]]

In [69]:
np.matmul (a,b)

array([[19, 22],
       [38, 44]])

In [77]:
#Write a NumPy program to create a 3x3 identity matrix

matrixx = np.identity(3)
matrixx

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10
matricxx = np.arange(2,11). reshape(3,3)
matricxx

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [53]:
#Write a NumPy program to create a new shape to an array without changing its data(for example a 3X2 matrix to a 2x3 matrix)
nn = np.arange(6). reshape (3,2)
nn

array([[0, 1],
       [2, 3],
       [4, 5]])

In [54]:
nn.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])